name: banking_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.0.9
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/bank_logo1.png
    - assets/images/splash.png


  uses-material-design: true
